name: Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Version packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Read .nvmrc
        id: node_version
        run: echo NODE_VERSION=$(cat .nvmrc) >> $GITHUB_OUTPUT

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install

      - name: Create and publish versions
        uses: changesets/action@v1
        with:
          title: "chore(@pkg-tools/*): update package versions"
          commit: "chore(@pkg-tools/*): update package versions"
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.PULL_REQUEST_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PKG_TOOLS_SCOPE_PUBLISH_TOKEN }}
            
